apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: bouzakri/cast-service:latest  
        command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "4000"]
        env:
        - name: DATABASE_URI
          value: "postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
spec:
  selector:
    app: cast-service
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
