apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: bouzakri/movie-service:latest 
        command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "3000"]
        env:
        - name: DATABASE_URI
          value: "postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev"
        - name: CAST_SERVICE_HOST_URL
          value: "http://192.168.1.4:32000/api/v1/casts/"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  type: NodePort
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
